# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0002_auto_20170912_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='app_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='mana_ip',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='mana_pass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='order_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
