# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0003_auto_20170913_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='place_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
