# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0004_cmdb_place_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='mana_ip',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
