# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0005_auto_20170914_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=200)),
                ('oa1', models.CharField(max_length=200)),
                ('oa2', models.CharField(max_length=200)),
                ('vc1', models.CharField(max_length=200)),
                ('vc2', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('zhiwei', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yto_cmdb.idc'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='cabinet_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yto_cmdb.cabinet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='container_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yto_cmdb.container'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='people_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yto_cmdb.people'),
            preserve_default=False,
        ),
    ]
