# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0006_auto_20170918_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='oa1_pass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='oa2_pass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='vc1_pass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='vc2_pass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
