# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0007_auto_20170918_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='oa1',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='oa2',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='vc1',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='vc2',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
