# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yto_cmdb', '0008_auto_20170919_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_text', models.CharField(max_length=200, unique=True)),
                ('app_text', models.CharField(max_length=200)),
                ('order_text', models.CharField(max_length=200)),
                ('os_text', models.CharField(max_length=200)),
                ('pool_text', models.CharField(max_length=200)),
                ('user_text', models.CharField(max_length=200)),
                ('pass_text', models.CharField(max_length=200)),
                ('cpu_text', models.CharField(max_length=200)),
                ('mem_text', models.CharField(max_length=200)),
                ('disk_text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vm_cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_cluster_name', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vm',
            name='vm_cluster_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yto_cmdb.vm_cluster'),
        ),
    ]
